services:
  - type: web
    name: router-tracker
    runtime: python
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
